---
toc: false
---
# Acknowledgements {.unnumbered}


<blockquote class="twitter-tweet"><p lang="zxx" dir="ltr"><a href="https://t.co/jiI6k0xJzF">pic.twitter.com/jiI6k0xJzF</a></p>&mdash; BREADSWORD (@BREADSWORD) <a href="https://twitter.com/BREADSWORD/status/1552075956751200258?ref_src=twsrc%5Etfw">July 26, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

This thesis could not be completed without the invaluable support I received from others.
I’ll begin by thanking my supervisors A/Prof. Ebinazar Namdas, A/Prof Shih-Chun Lo
(Lawrence), and Dr Atul Shukla. Each of these individuals have tolerated my shenanigans
throughout the year. Without their patience and expertise, I would not be where I am
today. Similarly, thank you to the COPE team for listening to me ramble and struggle my
way through this thesis.


I want to next thank my family who have always got my back. To my mother, even
though I may waterboard you with nonsense physics, the calls and conversations you have
endured do not go underappreciated. To my father, your work ethic has inspired me to
always keep pushing, even when this thesis seemed unobtainable ”Dad would have kept
going, so will I”, I would think. To the brothers of mine, the Civil Trio, I now have this huge
document, I guess – I don’t recommend it. I love you all.


To my family away from home, Tamar Street. You’ve kept me humble by reminding me
to ”leave the thinking to the intellectuals”; you’ve reminded me to relax and have fun in a
year of doubt and stress; you’ve pushed me to do the things I love and be more of myself
than ever. Sam with basketball, Spencer with gym, Will with yarns, Doug with F1, Laura
with movies, Mia with intellectual-discussions, Sarah with yard-bevvies, Nicola with gossip,
Cass with mental-support: all of you are fantastic.


To myself, well done, bud. You got there. Not the way we imagined at the start, but we
finished. Remember why you did this, but don’t forget what you learned while doing this.


Trust The Process.