---
toc: false
execute: 
  enabled: false
---
# Preface {.unnumbered}

> "Explorers are we, intrepid and bold, out in the wild, amongst wonders untold. Equipped with our wits, a map, and a snack; we're searching for fun and we're on the right track!" - Calvin and Hobbes

When I first started my honours thesis, I was excited at for what lied ahead. I was oozing confidence, naively arrogant, that I was going to achieve so much. While it isn’t a thesis worthy of the lofty expectations, it is completed. And more importantly I learned a lot. 

Maybe the best way to get you excited about my thesis, is to tell you why I was so excited about it when I first started.
I’m a technology-inclined guy. So, I was aware of OLEDs, organic light emitting diodes, before I was introduced to them in the physics context. OLEDs were, and still are, everywhere on the forefront of display technology. You can find them as the screen for every [modern phone](https://support.apple.com/en-us/HT208191), or even on the new [Nintendo OLED Switch](https://www.nintendo.com/switch/oled-model/) (valued at roughly $100 more). Or if you go to the any TV distributor, the OLEDs are clearly the priciest and highest quality looking [TVs](https://www.whathifi.com/best-buys/tvs/best-oled-tvs). If you wanted a good screen, the device should be using OLEDs – that much I knew. 

What I didn’t know would come next. It never clicked for awhile that OLEDs were just Organic LEDs.  Organic in the sense they are made of carbon-based molecules. We’ll touch on later why that is important. But I’ll spoil the main interesting part of that now. If it is organic, it is really easy to alter the structure of the molecule to fine-tune the properties of the OLED. You can likely make the link yourself that this opens the possibility of doing so much, not only in terms of efficiency in manufacturing, but also making new things altogether. This is where the idea for organic lasers came about. 

Organic lasers, like regular lasers, but as before made from carbon-based molecules. If you’re a tech person, you might already know that there aren’t any organic lasers on the Coles shelves yet. In fact, no one has been able to make organic lasers (at the time of writing). Again, it’d be rude to giveaway the entire reason why now, but organic materials have a handicap that makes it difficult to get the energy output a laser requires.  

This is where my thesis comes into it. I set out to, while not exactly make a laser, but test a very promising organic material and see whether it meets the lasing requirements. The material, [2,6-diphenylanthracene (2,6-DPA)](https://pubchem.ncbi.nlm.nih.gov/compound/2_6-Diphenylanthracene), is promising because it may exhibit a neat function that may overcome the handicap that I talked about earlier. 

That is about it for an introduction, without getting into the nitty gritty. But I will include my abstract below with all the jargon in it for those who want a summary of the above in fewer words. 

# Abstract

> Lasers have left an indelible mark on science and technology, from applications ranging
from medicine to telecommunications to spectroscopy – we are even starting to see laser
televisions. To this day, no one has realised organic laser diodes despite the rapid and burgeoning
success of organic semiconductors. This failure is because an organic laser diode
needs to be injected with high current densities to achieve lasing, a threshold that seems
out of reach because of the inherent losses caused by the non-emissive triplet excited states.
Managing these excited states, or better yet turning them into emissive singlet states, lies
at the focus of realising organic lasers. This thesis will demonstrate the exciting potential
of using triplet-triplet upconversion – a process that annihilates two triplets to form the
emissive singlets – to help reduce the current density threshold. I argue for the lasing potential
of the highly emissive lasing material 3-(2-Benzothiazolyl)-N,N-diethylumbelliferylamine
(Coumarin6) when doped into 2,6-diphenylanthracene (2,6-DPA) that herein is confirmed to
exhibit triplet-triplet upconversion.